version: '3.9'
services:
  registry-db:
    container_name: messaging-hub-registry-db
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
      - ./containers/registry-db/schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - kaf-net
    environment:
      PGHOST: 0.0.0.0
      PGPORT: 5432
      PGDATABASE: dht
      PGUSER: scott
      POSTGRES_PASSWORD: tiger

  registry-app:
    container_name: messaging-hub-schema-registry-app
    image: thebookpeople/hortonworks-registry:latest
    ports:
      - 9090:9090
    networks:
      - kaf-net
    environment:
      DB_NAME: db
      DB_USER: scott
      DB_PASSWORD: tiger
      DB_PORT: 3306
      DB_HOST: registry-db
      REGISTRY_HEAP_OPTS: "-Xmx16G -Xms1G"
    depends_on:
      - registry-db

networks:
  dp-messaging-hub-registry-net:
    driver: bridge
