/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "gcdlcmservice_constants.h"

namespace mayton { namespace gcdlcm {

const gcdlcmserviceConstants g_gcdlcmservice_constants;

gcdlcmserviceConstants::gcdlcmserviceConstants() {
}

}} // namespace

