/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef gcdlcmservice_CONSTANTS_H
#define gcdlcmservice_CONSTANTS_H

#include "gcdlcmservice_types.h"

namespace mayton { namespace gcdlcm {

class gcdlcmserviceConstants {
 public:
  gcdlcmserviceConstants();

};

extern const gcdlcmserviceConstants g_gcdlcmservice_constants;

}} // namespace

#endif
