// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto3/member.proto

package ru.sql;

/**
 * Protobuf type {@code ru.sql.Member}
 */
public  final class Member extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:ru.sql.Member)
    MemberOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Member.newBuilder() to construct.
  private Member(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Member() {
    mid_ = 0;
    name_ = "";
    status_ = 0;
    email_ = "";
    url_ = "";
    icq_ = "";
    fromWhere_ = "";
    interests_ = "";
    job_ = "";
    info_ = "";
    messages_ = 0;
    registered_ = "";
    lastMessage_ = "";
    messagesPerDay_ = 0F;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return ru.sql.MemberOuterClass.internal_static_ru_sql_Member_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return ru.sql.MemberOuterClass.internal_static_ru_sql_Member_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            ru.sql.Member.class, ru.sql.Member.Builder.class);
  }

  /**
   * Protobuf enum {@code ru.sql.Member.Status}
   */
  public enum Status
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ADMIN = 0;</code>
     */
    ADMIN(0),
    /**
     * <code>REGISTERED = 1;</code>
     */
    REGISTERED(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ADMIN = 0;</code>
     */
    public static final int ADMIN_VALUE = 0;
    /**
     * <code>REGISTERED = 1;</code>
     */
    public static final int REGISTERED_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Status valueOf(int value) {
      return forNumber(value);
    }

    public static Status forNumber(int value) {
      switch (value) {
        case 0: return ADMIN;
        case 1: return REGISTERED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Status> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Status>() {
            public Status findValueByNumber(int number) {
              return Status.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return ru.sql.Member.getDescriptor().getEnumTypes().get(0);
    }

    private static final Status[] VALUES = values();

    public static Status valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Status(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:ru.sql.Member.Status)
  }

  public static final int MID_FIELD_NUMBER = 1;
  private int mid_;
  /**
   * <code>int32 mid = 1;</code>
   */
  public int getMid() {
    return mid_;
  }

  public static final int NAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object name_;
  /**
   * <pre>
   * // Имя
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * // Имя
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 3;
  private int status_;
  /**
   * <code>.ru.sql.Member.Status status = 3;</code>
   */
  public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.ru.sql.Member.Status status = 3;</code>
   */
  public ru.sql.Member.Status getStatus() {
    @SuppressWarnings("deprecation")
    ru.sql.Member.Status result = ru.sql.Member.Status.valueOf(status_);
    return result == null ? ru.sql.Member.Status.UNRECOGNIZED : result;
  }

  public static final int EMAIL_FIELD_NUMBER = 4;
  private volatile java.lang.Object email_;
  /**
   * <pre>
   * E-Mail:
   * </pre>
   *
   * <code>string email = 4;</code>
   */
  public java.lang.String getEmail() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      email_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * E-Mail:
   * </pre>
   *
   * <code>string email = 4;</code>
   */
  public com.google.protobuf.ByteString
      getEmailBytes() {
    java.lang.Object ref = email_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      email_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int URL_FIELD_NUMBER = 5;
  private volatile java.lang.Object url_;
  /**
   * <code>string url = 5;</code>
   */
  public java.lang.String getUrl() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      url_ = s;
      return s;
    }
  }
  /**
   * <code>string url = 5;</code>
   */
  public com.google.protobuf.ByteString
      getUrlBytes() {
    java.lang.Object ref = url_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      url_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int ICQ_FIELD_NUMBER = 6;
  private volatile java.lang.Object icq_;
  /**
   * <code>string icq = 6 [deprecated = true];</code>
   */
  @java.lang.Deprecated public java.lang.String getIcq() {
    java.lang.Object ref = icq_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      icq_ = s;
      return s;
    }
  }
  /**
   * <code>string icq = 6 [deprecated = true];</code>
   */
  @java.lang.Deprecated public com.google.protobuf.ByteString
      getIcqBytes() {
    java.lang.Object ref = icq_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      icq_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int FROM_WHERE_FIELD_NUMBER = 7;
  private volatile java.lang.Object fromWhere_;
  /**
   * <pre>
   * Откуда:
   * </pre>
   *
   * <code>string from_where = 7;</code>
   */
  public java.lang.String getFromWhere() {
    java.lang.Object ref = fromWhere_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      fromWhere_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Откуда:
   * </pre>
   *
   * <code>string from_where = 7;</code>
   */
  public com.google.protobuf.ByteString
      getFromWhereBytes() {
    java.lang.Object ref = fromWhere_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      fromWhere_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INTERESTS_FIELD_NUMBER = 8;
  private volatile java.lang.Object interests_;
  /**
   * <pre>
   * Интересы:
   * </pre>
   *
   * <code>string interests = 8;</code>
   */
  public java.lang.String getInterests() {
    java.lang.Object ref = interests_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      interests_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Интересы:
   * </pre>
   *
   * <code>string interests = 8;</code>
   */
  public com.google.protobuf.ByteString
      getInterestsBytes() {
    java.lang.Object ref = interests_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      interests_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JOB_FIELD_NUMBER = 9;
  private volatile java.lang.Object job_;
  /**
   * <pre>
   * Работа:
   * </pre>
   *
   * <code>string job = 9;</code>
   */
  public java.lang.String getJob() {
    java.lang.Object ref = job_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      job_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Работа:
   * </pre>
   *
   * <code>string job = 9;</code>
   */
  public com.google.protobuf.ByteString
      getJobBytes() {
    java.lang.Object ref = job_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      job_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int INFO_FIELD_NUMBER = 10;
  private volatile java.lang.Object info_;
  /**
   * <pre>
   * Информация:
   * </pre>
   *
   * <code>string info = 10;</code>
   */
  public java.lang.String getInfo() {
    java.lang.Object ref = info_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      info_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Информация:
   * </pre>
   *
   * <code>string info = 10;</code>
   */
  public com.google.protobuf.ByteString
      getInfoBytes() {
    java.lang.Object ref = info_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      info_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGES_FIELD_NUMBER = 11;
  private int messages_;
  /**
   * <pre>
   * Сообщений:
   * </pre>
   *
   * <code>int32 messages = 11;</code>
   */
  public int getMessages() {
    return messages_;
  }

  public static final int REGISTERED_FIELD_NUMBER = 12;
  private volatile java.lang.Object registered_;
  /**
   * <pre>
   * Зарегистрирован:  (date)
   * </pre>
   *
   * <code>string registered = 12;</code>
   */
  public java.lang.String getRegistered() {
    java.lang.Object ref = registered_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      registered_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Зарегистрирован:  (date)
   * </pre>
   *
   * <code>string registered = 12;</code>
   */
  public com.google.protobuf.ByteString
      getRegisteredBytes() {
    java.lang.Object ref = registered_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      registered_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LAST_MESSAGE_FIELD_NUMBER = 13;
  private volatile java.lang.Object lastMessage_;
  /**
   * <pre>
   * Последнее сообщение:  (date)
   * </pre>
   *
   * <code>string last_message = 13;</code>
   */
  public java.lang.String getLastMessage() {
    java.lang.Object ref = lastMessage_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      lastMessage_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Последнее сообщение:  (date)
   * </pre>
   *
   * <code>string last_message = 13;</code>
   */
  public com.google.protobuf.ByteString
      getLastMessageBytes() {
    java.lang.Object ref = lastMessage_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      lastMessage_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int MESSAGES_PER_DAY_FIELD_NUMBER = 14;
  private float messagesPerDay_;
  /**
   * <pre>
   * Сообщений в день: ex: 0,021
   * </pre>
   *
   * <code>float messages_per_day = 14;</code>
   */
  public float getMessagesPerDay() {
    return messagesPerDay_;
  }

  public static ru.sql.Member parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.sql.Member parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.sql.Member parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.sql.Member parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.sql.Member parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static ru.sql.Member parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static ru.sql.Member parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.sql.Member parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.sql.Member parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static ru.sql.Member parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static ru.sql.Member parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static ru.sql.Member parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(ru.sql.Member prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code ru.sql.Member}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:ru.sql.Member)
      ru.sql.MemberOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return ru.sql.MemberOuterClass.internal_static_ru_sql_Member_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return ru.sql.MemberOuterClass.internal_static_ru_sql_Member_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              ru.sql.Member.class, ru.sql.Member.Builder.class);
    }

    // Construct using ru.sql.Member.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      mid_ = 0;

      name_ = "";

      status_ = 0;

      email_ = "";

      url_ = "";

      icq_ = "";

      fromWhere_ = "";

      interests_ = "";

      job_ = "";

      info_ = "";

      messages_ = 0;

      registered_ = "";

      lastMessage_ = "";

      messagesPerDay_ = 0F;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return ru.sql.MemberOuterClass.internal_static_ru_sql_Member_descriptor;
    }

    @java.lang.Override
    public ru.sql.Member getDefaultInstanceForType() {
      return ru.sql.Member.getDefaultInstance();
    }

    @java.lang.Override
    public ru.sql.Member build() {
      ru.sql.Member result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public ru.sql.Member buildPartial() {
      ru.sql.Member result = new ru.sql.Member(this);
      result.mid_ = mid_;
      result.name_ = name_;
      result.status_ = status_;
      result.email_ = email_;
      result.url_ = url_;
      result.icq_ = icq_;
      result.fromWhere_ = fromWhere_;
      result.interests_ = interests_;
      result.job_ = job_;
      result.info_ = info_;
      result.messages_ = messages_;
      result.registered_ = registered_;
      result.lastMessage_ = lastMessage_;
      result.messagesPerDay_ = messagesPerDay_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }

    private int mid_ ;
    /**
     * <code>int32 mid = 1;</code>
     */
    public int getMid() {
      return mid_;
    }
    /**
     * <code>int32 mid = 1;</code>
     */
    public Builder setMid(int value) {
      
      mid_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 mid = 1;</code>
     */
    public Builder clearMid() {
      
      mid_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <pre>
     * // Имя
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * // Имя
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * // Имя
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      name_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * // Имя
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder clearName() {
      
      name_ = getDefaultInstance().getName();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * // Имя
     * </pre>
     *
     * <code>string name = 2;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      name_ = value;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.ru.sql.Member.Status status = 3;</code>
     */
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.ru.sql.Member.Status status = 3;</code>
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.ru.sql.Member.Status status = 3;</code>
     */
    public ru.sql.Member.Status getStatus() {
      @SuppressWarnings("deprecation")
      ru.sql.Member.Status result = ru.sql.Member.Status.valueOf(status_);
      return result == null ? ru.sql.Member.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.ru.sql.Member.Status status = 3;</code>
     */
    public Builder setStatus(ru.sql.Member.Status value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.ru.sql.Member.Status status = 3;</code>
     */
    public Builder clearStatus() {
      
      status_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object email_ = "";
    /**
     * <pre>
     * E-Mail:
     * </pre>
     *
     * <code>string email = 4;</code>
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * E-Mail:
     * </pre>
     *
     * <code>string email = 4;</code>
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * E-Mail:
     * </pre>
     *
     * <code>string email = 4;</code>
     */
    public Builder setEmail(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      email_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * E-Mail:
     * </pre>
     *
     * <code>string email = 4;</code>
     */
    public Builder clearEmail() {
      
      email_ = getDefaultInstance().getEmail();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * E-Mail:
     * </pre>
     *
     * <code>string email = 4;</code>
     */
    public Builder setEmailBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      email_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object url_ = "";
    /**
     * <code>string url = 5;</code>
     */
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string url = 5;</code>
     */
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string url = 5;</code>
     */
    public Builder setUrl(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      url_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string url = 5;</code>
     */
    public Builder clearUrl() {
      
      url_ = getDefaultInstance().getUrl();
      onChanged();
      return this;
    }
    /**
     * <code>string url = 5;</code>
     */
    public Builder setUrlBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      url_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object icq_ = "";
    /**
     * <code>string icq = 6 [deprecated = true];</code>
     */
    @java.lang.Deprecated public java.lang.String getIcq() {
      java.lang.Object ref = icq_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        icq_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string icq = 6 [deprecated = true];</code>
     */
    @java.lang.Deprecated public com.google.protobuf.ByteString
        getIcqBytes() {
      java.lang.Object ref = icq_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        icq_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string icq = 6 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder setIcq(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      icq_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string icq = 6 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder clearIcq() {
      
      icq_ = getDefaultInstance().getIcq();
      onChanged();
      return this;
    }
    /**
     * <code>string icq = 6 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder setIcqBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      icq_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object fromWhere_ = "";
    /**
     * <pre>
     * Откуда:
     * </pre>
     *
     * <code>string from_where = 7;</code>
     */
    public java.lang.String getFromWhere() {
      java.lang.Object ref = fromWhere_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        fromWhere_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Откуда:
     * </pre>
     *
     * <code>string from_where = 7;</code>
     */
    public com.google.protobuf.ByteString
        getFromWhereBytes() {
      java.lang.Object ref = fromWhere_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        fromWhere_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Откуда:
     * </pre>
     *
     * <code>string from_where = 7;</code>
     */
    public Builder setFromWhere(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      fromWhere_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Откуда:
     * </pre>
     *
     * <code>string from_where = 7;</code>
     */
    public Builder clearFromWhere() {
      
      fromWhere_ = getDefaultInstance().getFromWhere();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Откуда:
     * </pre>
     *
     * <code>string from_where = 7;</code>
     */
    public Builder setFromWhereBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      fromWhere_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object interests_ = "";
    /**
     * <pre>
     * Интересы:
     * </pre>
     *
     * <code>string interests = 8;</code>
     */
    public java.lang.String getInterests() {
      java.lang.Object ref = interests_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        interests_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Интересы:
     * </pre>
     *
     * <code>string interests = 8;</code>
     */
    public com.google.protobuf.ByteString
        getInterestsBytes() {
      java.lang.Object ref = interests_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        interests_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Интересы:
     * </pre>
     *
     * <code>string interests = 8;</code>
     */
    public Builder setInterests(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      interests_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Интересы:
     * </pre>
     *
     * <code>string interests = 8;</code>
     */
    public Builder clearInterests() {
      
      interests_ = getDefaultInstance().getInterests();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Интересы:
     * </pre>
     *
     * <code>string interests = 8;</code>
     */
    public Builder setInterestsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      interests_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object job_ = "";
    /**
     * <pre>
     * Работа:
     * </pre>
     *
     * <code>string job = 9;</code>
     */
    public java.lang.String getJob() {
      java.lang.Object ref = job_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        job_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Работа:
     * </pre>
     *
     * <code>string job = 9;</code>
     */
    public com.google.protobuf.ByteString
        getJobBytes() {
      java.lang.Object ref = job_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        job_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Работа:
     * </pre>
     *
     * <code>string job = 9;</code>
     */
    public Builder setJob(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      job_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Работа:
     * </pre>
     *
     * <code>string job = 9;</code>
     */
    public Builder clearJob() {
      
      job_ = getDefaultInstance().getJob();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Работа:
     * </pre>
     *
     * <code>string job = 9;</code>
     */
    public Builder setJobBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      job_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object info_ = "";
    /**
     * <pre>
     * Информация:
     * </pre>
     *
     * <code>string info = 10;</code>
     */
    public java.lang.String getInfo() {
      java.lang.Object ref = info_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        info_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Информация:
     * </pre>
     *
     * <code>string info = 10;</code>
     */
    public com.google.protobuf.ByteString
        getInfoBytes() {
      java.lang.Object ref = info_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        info_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Информация:
     * </pre>
     *
     * <code>string info = 10;</code>
     */
    public Builder setInfo(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      info_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Информация:
     * </pre>
     *
     * <code>string info = 10;</code>
     */
    public Builder clearInfo() {
      
      info_ = getDefaultInstance().getInfo();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Информация:
     * </pre>
     *
     * <code>string info = 10;</code>
     */
    public Builder setInfoBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      info_ = value;
      onChanged();
      return this;
    }

    private int messages_ ;
    /**
     * <pre>
     * Сообщений:
     * </pre>
     *
     * <code>int32 messages = 11;</code>
     */
    public int getMessages() {
      return messages_;
    }
    /**
     * <pre>
     * Сообщений:
     * </pre>
     *
     * <code>int32 messages = 11;</code>
     */
    public Builder setMessages(int value) {
      
      messages_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Сообщений:
     * </pre>
     *
     * <code>int32 messages = 11;</code>
     */
    public Builder clearMessages() {
      
      messages_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object registered_ = "";
    /**
     * <pre>
     * Зарегистрирован:  (date)
     * </pre>
     *
     * <code>string registered = 12;</code>
     */
    public java.lang.String getRegistered() {
      java.lang.Object ref = registered_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        registered_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Зарегистрирован:  (date)
     * </pre>
     *
     * <code>string registered = 12;</code>
     */
    public com.google.protobuf.ByteString
        getRegisteredBytes() {
      java.lang.Object ref = registered_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        registered_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Зарегистрирован:  (date)
     * </pre>
     *
     * <code>string registered = 12;</code>
     */
    public Builder setRegistered(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      registered_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Зарегистрирован:  (date)
     * </pre>
     *
     * <code>string registered = 12;</code>
     */
    public Builder clearRegistered() {
      
      registered_ = getDefaultInstance().getRegistered();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Зарегистрирован:  (date)
     * </pre>
     *
     * <code>string registered = 12;</code>
     */
    public Builder setRegisteredBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      registered_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object lastMessage_ = "";
    /**
     * <pre>
     * Последнее сообщение:  (date)
     * </pre>
     *
     * <code>string last_message = 13;</code>
     */
    public java.lang.String getLastMessage() {
      java.lang.Object ref = lastMessage_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        lastMessage_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Последнее сообщение:  (date)
     * </pre>
     *
     * <code>string last_message = 13;</code>
     */
    public com.google.protobuf.ByteString
        getLastMessageBytes() {
      java.lang.Object ref = lastMessage_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        lastMessage_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Последнее сообщение:  (date)
     * </pre>
     *
     * <code>string last_message = 13;</code>
     */
    public Builder setLastMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      lastMessage_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Последнее сообщение:  (date)
     * </pre>
     *
     * <code>string last_message = 13;</code>
     */
    public Builder clearLastMessage() {
      
      lastMessage_ = getDefaultInstance().getLastMessage();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Последнее сообщение:  (date)
     * </pre>
     *
     * <code>string last_message = 13;</code>
     */
    public Builder setLastMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      lastMessage_ = value;
      onChanged();
      return this;
    }

    private float messagesPerDay_ ;
    /**
     * <pre>
     * Сообщений в день: ex: 0,021
     * </pre>
     *
     * <code>float messages_per_day = 14;</code>
     */
    public float getMessagesPerDay() {
      return messagesPerDay_;
    }
    /**
     * <pre>
     * Сообщений в день: ex: 0,021
     * </pre>
     *
     * <code>float messages_per_day = 14;</code>
     */
    public Builder setMessagesPerDay(float value) {
      
      messagesPerDay_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Сообщений в день: ex: 0,021
     * </pre>
     *
     * <code>float messages_per_day = 14;</code>
     */
    public Builder clearMessagesPerDay() {
      
      messagesPerDay_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:ru.sql.Member)
  }

  // @@protoc_insertion_point(class_scope:ru.sql.Member)
  private static final ru.sql.Member DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new ru.sql.Member();
  }

  public static ru.sql.Member getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Member>
      PARSER = new com.google.protobuf.AbstractParser<Member>() {
    @java.lang.Override
    public Member parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(
                builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Member> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Member> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public ru.sql.Member getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

