// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto3/member.proto

package ru.sql;

public final class MemberOuterClass {
  private MemberOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ru_sql_Member_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ru_sql_Member_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023proto3/member.proto\022\006ru.sql\"\264\002\n\006Member" +
      "\022\013\n\003mid\030\001 \001(\005\022\014\n\004name\030\002 \001(\t\022%\n\006status\030\003 " +
      "\001(\0162\025.ru.sql.Member.Status\022\r\n\005email\030\004 \001(" +
      "\t\022\013\n\003url\030\005 \001(\t\022\017\n\003icq\030\006 \001(\tB\002\030\001\022\022\n\nfrom_" +
      "where\030\007 \001(\t\022\021\n\tinterests\030\010 \001(\t\022\013\n\003job\030\t " +
      "\001(\t\022\014\n\004info\030\n \001(\t\022\020\n\010messages\030\013 \001(\005\022\022\n\nr" +
      "egistered\030\014 \001(\t\022\024\n\014last_message\030\r \001(\t\022\030\n" +
      "\020messages_per_day\030\016 \001(\002\"#\n\006Status\022\t\n\005ADM" +
      "IN\020\000\022\016\n\nREGISTERED\020\001B\014\n\006ru.sqlH\002P\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_ru_sql_Member_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ru_sql_Member_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ru_sql_Member_descriptor,
        new java.lang.String[] { "Mid", "Name", "Status", "Email", "Url", "Icq", "FromWhere", "Interests", "Job", "Info", "Messages", "Registered", "LastMessage", "MessagesPerDay", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
