// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto3/emp.proto

package mayton.emp;

/**
 * <pre>
 * DEPTNO;DNAME;LOC
 * </pre>
 *
 * Protobuf type {@code mayton.geo.Debt}
 */
public  final class Debt extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mayton.geo.Debt)
    DebtOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Debt.newBuilder() to construct.
  private Debt(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Debt() {
    deptNo_ = 0;
    debtName_ = "";
    loc_ = "";
    emps_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return mayton.emp.EmpOuterClass.internal_static_mayton_geo_Debt_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return mayton.emp.EmpOuterClass.internal_static_mayton_geo_Debt_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            mayton.emp.Debt.class, mayton.emp.Debt.Builder.class);
  }

  private int bitField0_;
  public static final int DEPTNO_FIELD_NUMBER = 1;
  private int deptNo_;
  /**
   * <code>int32 deptNo = 1;</code>
   */
  public int getDeptNo() {
    return deptNo_;
  }

  public static final int DEBTNAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object debtName_;
  /**
   * <code>string debtName = 2;</code>
   */
  public java.lang.String getDebtName() {
    java.lang.Object ref = debtName_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      debtName_ = s;
      return s;
    }
  }
  /**
   * <code>string debtName = 2;</code>
   */
  public com.google.protobuf.ByteString
      getDebtNameBytes() {
    java.lang.Object ref = debtName_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      debtName_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int LOC_FIELD_NUMBER = 3;
  private volatile java.lang.Object loc_;
  /**
   * <code>string loc = 3;</code>
   */
  public java.lang.String getLoc() {
    java.lang.Object ref = loc_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      loc_ = s;
      return s;
    }
  }
  /**
   * <code>string loc = 3;</code>
   */
  public com.google.protobuf.ByteString
      getLocBytes() {
    java.lang.Object ref = loc_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      loc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int EMPS_FIELD_NUMBER = 4;
  private java.util.List<mayton.emp.Emp> emps_;
  /**
   * <code>repeated .mayton.geo.Emp emps = 4;</code>
   */
  public java.util.List<mayton.emp.Emp> getEmpsList() {
    return emps_;
  }
  /**
   * <code>repeated .mayton.geo.Emp emps = 4;</code>
   */
  public java.util.List<? extends mayton.emp.EmpOrBuilder> 
      getEmpsOrBuilderList() {
    return emps_;
  }
  /**
   * <code>repeated .mayton.geo.Emp emps = 4;</code>
   */
  public int getEmpsCount() {
    return emps_.size();
  }
  /**
   * <code>repeated .mayton.geo.Emp emps = 4;</code>
   */
  public mayton.emp.Emp getEmps(int index) {
    return emps_.get(index);
  }
  /**
   * <code>repeated .mayton.geo.Emp emps = 4;</code>
   */
  public mayton.emp.EmpOrBuilder getEmpsOrBuilder(
      int index) {
    return emps_.get(index);
  }

  public static final int ANYOBJECT_FIELD_NUMBER = 5;
  private com.google.protobuf.Any anyObject_;
  /**
   * <code>.google.protobuf.Any anyObject = 5;</code>
   */
  public boolean hasAnyObject() {
    return anyObject_ != null;
  }
  /**
   * <code>.google.protobuf.Any anyObject = 5;</code>
   */
  public com.google.protobuf.Any getAnyObject() {
    return anyObject_ == null ? com.google.protobuf.Any.getDefaultInstance() : anyObject_;
  }
  /**
   * <code>.google.protobuf.Any anyObject = 5;</code>
   */
  public com.google.protobuf.AnyOrBuilder getAnyObjectOrBuilder() {
    return getAnyObject();
  }

  public static mayton.emp.Debt parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mayton.emp.Debt parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mayton.emp.Debt parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mayton.emp.Debt parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mayton.emp.Debt parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mayton.emp.Debt parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mayton.emp.Debt parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static mayton.emp.Debt parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static mayton.emp.Debt parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static mayton.emp.Debt parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static mayton.emp.Debt parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static mayton.emp.Debt parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(mayton.emp.Debt prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * DEPTNO;DNAME;LOC
   * </pre>
   *
   * Protobuf type {@code mayton.geo.Debt}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mayton.geo.Debt)
      mayton.emp.DebtOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mayton.emp.EmpOuterClass.internal_static_mayton_geo_Debt_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mayton.emp.EmpOuterClass.internal_static_mayton_geo_Debt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mayton.emp.Debt.class, mayton.emp.Debt.Builder.class);
    }

    // Construct using mayton.emp.Debt.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getEmpsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      deptNo_ = 0;

      debtName_ = "";

      loc_ = "";

      if (empsBuilder_ == null) {
        emps_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
      } else {
        empsBuilder_.clear();
      }
      if (anyObjectBuilder_ == null) {
        anyObject_ = null;
      } else {
        anyObject_ = null;
        anyObjectBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return mayton.emp.EmpOuterClass.internal_static_mayton_geo_Debt_descriptor;
    }

    @java.lang.Override
    public mayton.emp.Debt getDefaultInstanceForType() {
      return mayton.emp.Debt.getDefaultInstance();
    }

    @java.lang.Override
    public mayton.emp.Debt build() {
      mayton.emp.Debt result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public mayton.emp.Debt buildPartial() {
      mayton.emp.Debt result = new mayton.emp.Debt(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.deptNo_ = deptNo_;
      result.debtName_ = debtName_;
      result.loc_ = loc_;
      if (empsBuilder_ == null) {
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          emps_ = java.util.Collections.unmodifiableList(emps_);
          bitField0_ = (bitField0_ & ~0x00000008);
        }
        result.emps_ = emps_;
      } else {
        result.emps_ = empsBuilder_.build();
      }
      if (anyObjectBuilder_ == null) {
        result.anyObject_ = anyObject_;
      } else {
        result.anyObject_ = anyObjectBuilder_.build();
      }
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    private int bitField0_;

    private int deptNo_ ;
    /**
     * <code>int32 deptNo = 1;</code>
     */
    public int getDeptNo() {
      return deptNo_;
    }
    /**
     * <code>int32 deptNo = 1;</code>
     */
    public Builder setDeptNo(int value) {
      
      deptNo_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 deptNo = 1;</code>
     */
    public Builder clearDeptNo() {
      
      deptNo_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object debtName_ = "";
    /**
     * <code>string debtName = 2;</code>
     */
    public java.lang.String getDebtName() {
      java.lang.Object ref = debtName_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        debtName_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string debtName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getDebtNameBytes() {
      java.lang.Object ref = debtName_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        debtName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string debtName = 2;</code>
     */
    public Builder setDebtName(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      debtName_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string debtName = 2;</code>
     */
    public Builder clearDebtName() {
      
      debtName_ = getDefaultInstance().getDebtName();
      onChanged();
      return this;
    }
    /**
     * <code>string debtName = 2;</code>
     */
    public Builder setDebtNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      debtName_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object loc_ = "";
    /**
     * <code>string loc = 3;</code>
     */
    public java.lang.String getLoc() {
      java.lang.Object ref = loc_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        loc_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string loc = 3;</code>
     */
    public com.google.protobuf.ByteString
        getLocBytes() {
      java.lang.Object ref = loc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        loc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string loc = 3;</code>
     */
    public Builder setLoc(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      loc_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string loc = 3;</code>
     */
    public Builder clearLoc() {
      
      loc_ = getDefaultInstance().getLoc();
      onChanged();
      return this;
    }
    /**
     * <code>string loc = 3;</code>
     */
    public Builder setLocBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      loc_ = value;
      onChanged();
      return this;
    }

    private java.util.List<mayton.emp.Emp> emps_ =
      java.util.Collections.emptyList();
    private void ensureEmpsIsMutable() {
      if (!((bitField0_ & 0x00000008) == 0x00000008)) {
        emps_ = new java.util.ArrayList<mayton.emp.Emp>(emps_);
        bitField0_ |= 0x00000008;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        mayton.emp.Emp, mayton.emp.Emp.Builder, mayton.emp.EmpOrBuilder> empsBuilder_;

    /**
     * <code>repeated .mayton.geo.Emp emps = 4;</code>
     */
    public java.util.List<mayton.emp.Emp> getEmpsList() {
      if (empsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(emps_);
      } else {
        return empsBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .mayton.geo.Emp emps = 4;</code>
     */
    public int getEmpsCount() {
      if (empsBuilder_ == null) {
        return emps_.size();
      } else {
        return empsBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .mayton.geo.Emp emps = 4;</code>
     */
    public mayton.emp.Emp getEmps(int index) {
      if (empsBuilder_ == null) {
        return emps_.get(index);
      } else {
        return empsBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .mayton.geo.Emp emps = 4;</code>
     */
    public Builder setEmps(
        int index, mayton.emp.Emp value) {
      if (empsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmpsIsMutable();
        emps_.set(index, value);
        onChanged();
      } else {
        empsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mayton.geo.Emp emps = 4;</code>
     */
    public Builder setEmps(
        int index, mayton.emp.Emp.Builder builderForValue) {
      if (empsBuilder_ == null) {
        ensureEmpsIsMutable();
        emps_.set(index, builderForValue.build());
        onChanged();
      } else {
        empsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mayton.geo.Emp emps = 4;</code>
     */
    public Builder addEmps(mayton.emp.Emp value) {
      if (empsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmpsIsMutable();
        emps_.add(value);
        onChanged();
      } else {
        empsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .mayton.geo.Emp emps = 4;</code>
     */
    public Builder addEmps(
        int index, mayton.emp.Emp value) {
      if (empsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureEmpsIsMutable();
        emps_.add(index, value);
        onChanged();
      } else {
        empsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .mayton.geo.Emp emps = 4;</code>
     */
    public Builder addEmps(
        mayton.emp.Emp.Builder builderForValue) {
      if (empsBuilder_ == null) {
        ensureEmpsIsMutable();
        emps_.add(builderForValue.build());
        onChanged();
      } else {
        empsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mayton.geo.Emp emps = 4;</code>
     */
    public Builder addEmps(
        int index, mayton.emp.Emp.Builder builderForValue) {
      if (empsBuilder_ == null) {
        ensureEmpsIsMutable();
        emps_.add(index, builderForValue.build());
        onChanged();
      } else {
        empsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .mayton.geo.Emp emps = 4;</code>
     */
    public Builder addAllEmps(
        java.lang.Iterable<? extends mayton.emp.Emp> values) {
      if (empsBuilder_ == null) {
        ensureEmpsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, emps_);
        onChanged();
      } else {
        empsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .mayton.geo.Emp emps = 4;</code>
     */
    public Builder clearEmps() {
      if (empsBuilder_ == null) {
        emps_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
      } else {
        empsBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .mayton.geo.Emp emps = 4;</code>
     */
    public Builder removeEmps(int index) {
      if (empsBuilder_ == null) {
        ensureEmpsIsMutable();
        emps_.remove(index);
        onChanged();
      } else {
        empsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .mayton.geo.Emp emps = 4;</code>
     */
    public mayton.emp.Emp.Builder getEmpsBuilder(
        int index) {
      return getEmpsFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .mayton.geo.Emp emps = 4;</code>
     */
    public mayton.emp.EmpOrBuilder getEmpsOrBuilder(
        int index) {
      if (empsBuilder_ == null) {
        return emps_.get(index);  } else {
        return empsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .mayton.geo.Emp emps = 4;</code>
     */
    public java.util.List<? extends mayton.emp.EmpOrBuilder> 
         getEmpsOrBuilderList() {
      if (empsBuilder_ != null) {
        return empsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(emps_);
      }
    }
    /**
     * <code>repeated .mayton.geo.Emp emps = 4;</code>
     */
    public mayton.emp.Emp.Builder addEmpsBuilder() {
      return getEmpsFieldBuilder().addBuilder(
          mayton.emp.Emp.getDefaultInstance());
    }
    /**
     * <code>repeated .mayton.geo.Emp emps = 4;</code>
     */
    public mayton.emp.Emp.Builder addEmpsBuilder(
        int index) {
      return getEmpsFieldBuilder().addBuilder(
          index, mayton.emp.Emp.getDefaultInstance());
    }
    /**
     * <code>repeated .mayton.geo.Emp emps = 4;</code>
     */
    public java.util.List<mayton.emp.Emp.Builder> 
         getEmpsBuilderList() {
      return getEmpsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        mayton.emp.Emp, mayton.emp.Emp.Builder, mayton.emp.EmpOrBuilder> 
        getEmpsFieldBuilder() {
      if (empsBuilder_ == null) {
        empsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            mayton.emp.Emp, mayton.emp.Emp.Builder, mayton.emp.EmpOrBuilder>(
                emps_,
                ((bitField0_ & 0x00000008) == 0x00000008),
                getParentForChildren(),
                isClean());
        emps_ = null;
      }
      return empsBuilder_;
    }

    private com.google.protobuf.Any anyObject_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> anyObjectBuilder_;
    /**
     * <code>.google.protobuf.Any anyObject = 5;</code>
     */
    public boolean hasAnyObject() {
      return anyObjectBuilder_ != null || anyObject_ != null;
    }
    /**
     * <code>.google.protobuf.Any anyObject = 5;</code>
     */
    public com.google.protobuf.Any getAnyObject() {
      if (anyObjectBuilder_ == null) {
        return anyObject_ == null ? com.google.protobuf.Any.getDefaultInstance() : anyObject_;
      } else {
        return anyObjectBuilder_.getMessage();
      }
    }
    /**
     * <code>.google.protobuf.Any anyObject = 5;</code>
     */
    public Builder setAnyObject(com.google.protobuf.Any value) {
      if (anyObjectBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        anyObject_ = value;
        onChanged();
      } else {
        anyObjectBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any anyObject = 5;</code>
     */
    public Builder setAnyObject(
        com.google.protobuf.Any.Builder builderForValue) {
      if (anyObjectBuilder_ == null) {
        anyObject_ = builderForValue.build();
        onChanged();
      } else {
        anyObjectBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any anyObject = 5;</code>
     */
    public Builder mergeAnyObject(com.google.protobuf.Any value) {
      if (anyObjectBuilder_ == null) {
        if (anyObject_ != null) {
          anyObject_ =
            com.google.protobuf.Any.newBuilder(anyObject_).mergeFrom(value).buildPartial();
        } else {
          anyObject_ = value;
        }
        onChanged();
      } else {
        anyObjectBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any anyObject = 5;</code>
     */
    public Builder clearAnyObject() {
      if (anyObjectBuilder_ == null) {
        anyObject_ = null;
        onChanged();
      } else {
        anyObject_ = null;
        anyObjectBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.google.protobuf.Any anyObject = 5;</code>
     */
    public com.google.protobuf.Any.Builder getAnyObjectBuilder() {
      
      onChanged();
      return getAnyObjectFieldBuilder().getBuilder();
    }
    /**
     * <code>.google.protobuf.Any anyObject = 5;</code>
     */
    public com.google.protobuf.AnyOrBuilder getAnyObjectOrBuilder() {
      if (anyObjectBuilder_ != null) {
        return anyObjectBuilder_.getMessageOrBuilder();
      } else {
        return anyObject_ == null ?
            com.google.protobuf.Any.getDefaultInstance() : anyObject_;
      }
    }
    /**
     * <code>.google.protobuf.Any anyObject = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
        getAnyObjectFieldBuilder() {
      if (anyObjectBuilder_ == null) {
        anyObjectBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                getAnyObject(),
                getParentForChildren(),
                isClean());
        anyObject_ = null;
      }
      return anyObjectBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mayton.geo.Debt)
  }

  // @@protoc_insertion_point(class_scope:mayton.geo.Debt)
  private static final mayton.emp.Debt DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new mayton.emp.Debt();
  }

  public static mayton.emp.Debt getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Debt>
      PARSER = new com.google.protobuf.AbstractParser<Debt>() {
    @java.lang.Override
    public Debt parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(
                builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Debt> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Debt> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public mayton.emp.Debt getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

