// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto3/emp.proto

package mayton.emp;

public interface DebtOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mayton.geo.Debt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 deptNo = 1;</code>
   */
  int getDeptNo();

  /**
   * <code>string debtName = 2;</code>
   */
  java.lang.String getDebtName();
  /**
   * <code>string debtName = 2;</code>
   */
  com.google.protobuf.ByteString
      getDebtNameBytes();

  /**
   * <code>string loc = 3;</code>
   */
  java.lang.String getLoc();
  /**
   * <code>string loc = 3;</code>
   */
  com.google.protobuf.ByteString
      getLocBytes();

  /**
   * <code>repeated .mayton.geo.Emp emps = 4;</code>
   */
  java.util.List<mayton.emp.Emp> 
      getEmpsList();
  /**
   * <code>repeated .mayton.geo.Emp emps = 4;</code>
   */
  mayton.emp.Emp getEmps(int index);
  /**
   * <code>repeated .mayton.geo.Emp emps = 4;</code>
   */
  int getEmpsCount();
  /**
   * <code>repeated .mayton.geo.Emp emps = 4;</code>
   */
  java.util.List<? extends mayton.emp.EmpOrBuilder> 
      getEmpsOrBuilderList();
  /**
   * <code>repeated .mayton.geo.Emp emps = 4;</code>
   */
  mayton.emp.EmpOrBuilder getEmpsOrBuilder(
      int index);

  /**
   * <code>.google.protobuf.Any anyObject = 5;</code>
   */
  boolean hasAnyObject();
  /**
   * <code>.google.protobuf.Any anyObject = 5;</code>
   */
  com.google.protobuf.Any getAnyObject();
  /**
   * <code>.google.protobuf.Any anyObject = 5;</code>
   */
  com.google.protobuf.AnyOrBuilder getAnyObjectOrBuilder();
}
