// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto3/emp.proto

package mayton.emp;

/**
 * <pre>
 * EMPNO;ENAME;JOB;MGR;HIREDATE;SAL;COMM;DEPTNO
 * </pre>
 *
 * Protobuf type {@code mayton.geo.Emp}
 */
public  final class Emp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:mayton.geo.Emp)
    EmpOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Emp.newBuilder() to construct.
  private Emp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Emp() {
    empId_ = 0;
    ename_ = "";
    job_ = 0;
    mgr_ = 0;
    hiredate_ = "";
    sal_ = 0D;
    comm_ = 0D;
    comments_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return mayton.emp.EmpOuterClass.internal_static_mayton_geo_Emp_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return mayton.emp.EmpOuterClass.internal_static_mayton_geo_Emp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            mayton.emp.Emp.class, mayton.emp.Emp.Builder.class);
  }

  /**
   * Protobuf enum {@code mayton.geo.Emp.Jobs}
   */
  public enum Jobs
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>SALESMAN = 0;</code>
     */
    SALESMAN(0),
    /**
     * <code>PRESIDENT = 1;</code>
     */
    PRESIDENT(1),
    /**
     * <code>ANALYST = 2;</code>
     */
    ANALYST(2),
    /**
     * <code>CLERK = 3;</code>
     */
    CLERK(3),
    /**
     * <code>MANAGER = 4;</code>
     */
    MANAGER(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>SALESMAN = 0;</code>
     */
    public static final int SALESMAN_VALUE = 0;
    /**
     * <code>PRESIDENT = 1;</code>
     */
    public static final int PRESIDENT_VALUE = 1;
    /**
     * <code>ANALYST = 2;</code>
     */
    public static final int ANALYST_VALUE = 2;
    /**
     * <code>CLERK = 3;</code>
     */
    public static final int CLERK_VALUE = 3;
    /**
     * <code>MANAGER = 4;</code>
     */
    public static final int MANAGER_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Jobs valueOf(int value) {
      return forNumber(value);
    }

    public static Jobs forNumber(int value) {
      switch (value) {
        case 0: return SALESMAN;
        case 1: return PRESIDENT;
        case 2: return ANALYST;
        case 3: return CLERK;
        case 4: return MANAGER;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Jobs>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Jobs> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Jobs>() {
            public Jobs findValueByNumber(int number) {
              return Jobs.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return mayton.emp.Emp.getDescriptor().getEnumTypes().get(0);
    }

    private static final Jobs[] VALUES = values();

    public static Jobs valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Jobs(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:mayton.geo.Emp.Jobs)
  }

  public static final int EMPID_FIELD_NUMBER = 1;
  private int empId_;
  /**
   * <code>int32 empId = 1;</code>
   */
  public int getEmpId() {
    return empId_;
  }

  public static final int ENAME_FIELD_NUMBER = 2;
  private volatile java.lang.Object ename_;
  /**
   * <code>string ename = 2;</code>
   */
  public java.lang.String getEname() {
    java.lang.Object ref = ename_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      ename_ = s;
      return s;
    }
  }
  /**
   * <code>string ename = 2;</code>
   */
  public com.google.protobuf.ByteString
      getEnameBytes() {
    java.lang.Object ref = ename_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      ename_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int JOB_FIELD_NUMBER = 3;
  private int job_;
  /**
   * <code>.mayton.geo.Emp.Jobs job = 3;</code>
   */
  public int getJobValue() {
    return job_;
  }
  /**
   * <code>.mayton.geo.Emp.Jobs job = 3;</code>
   */
  public mayton.emp.Emp.Jobs getJob() {
    @SuppressWarnings("deprecation")
    mayton.emp.Emp.Jobs result = mayton.emp.Emp.Jobs.valueOf(job_);
    return result == null ? mayton.emp.Emp.Jobs.UNRECOGNIZED : result;
  }

  public static final int MGR_FIELD_NUMBER = 4;
  private int mgr_;
  /**
   * <code>int32 mgr = 4;</code>
   */
  public int getMgr() {
    return mgr_;
  }

  public static final int HIREDATE_FIELD_NUMBER = 5;
  private volatile java.lang.Object hiredate_;
  /**
   * <code>string hiredate = 5;</code>
   */
  public java.lang.String getHiredate() {
    java.lang.Object ref = hiredate_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      hiredate_ = s;
      return s;
    }
  }
  /**
   * <code>string hiredate = 5;</code>
   */
  public com.google.protobuf.ByteString
      getHiredateBytes() {
    java.lang.Object ref = hiredate_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      hiredate_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SAL_FIELD_NUMBER = 6;
  private double sal_;
  /**
   * <code>double sal = 6;</code>
   */
  public double getSal() {
    return sal_;
  }

  public static final int COMM_FIELD_NUMBER = 7;
  private double comm_;
  /**
   * <code>double comm = 7;</code>
   */
  public double getComm() {
    return comm_;
  }

  public static final int COMMENTS_FIELD_NUMBER = 8;
  private volatile java.lang.Object comments_;
  /**
   * <code>string comments = 8 [deprecated = true];</code>
   */
  @java.lang.Deprecated public java.lang.String getComments() {
    java.lang.Object ref = comments_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      comments_ = s;
      return s;
    }
  }
  /**
   * <code>string comments = 8 [deprecated = true];</code>
   */
  @java.lang.Deprecated public com.google.protobuf.ByteString
      getCommentsBytes() {
    java.lang.Object ref = comments_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      comments_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static mayton.emp.Emp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mayton.emp.Emp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mayton.emp.Emp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mayton.emp.Emp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mayton.emp.Emp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static mayton.emp.Emp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static mayton.emp.Emp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static mayton.emp.Emp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static mayton.emp.Emp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static mayton.emp.Emp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static mayton.emp.Emp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static mayton.emp.Emp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(mayton.emp.Emp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * EMPNO;ENAME;JOB;MGR;HIREDATE;SAL;COMM;DEPTNO
   * </pre>
   *
   * Protobuf type {@code mayton.geo.Emp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:mayton.geo.Emp)
      mayton.emp.EmpOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return mayton.emp.EmpOuterClass.internal_static_mayton_geo_Emp_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return mayton.emp.EmpOuterClass.internal_static_mayton_geo_Emp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              mayton.emp.Emp.class, mayton.emp.Emp.Builder.class);
    }

    // Construct using mayton.emp.Emp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      empId_ = 0;

      ename_ = "";

      job_ = 0;

      mgr_ = 0;

      hiredate_ = "";

      sal_ = 0D;

      comm_ = 0D;

      comments_ = "";

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return mayton.emp.EmpOuterClass.internal_static_mayton_geo_Emp_descriptor;
    }

    @java.lang.Override
    public mayton.emp.Emp getDefaultInstanceForType() {
      return mayton.emp.Emp.getDefaultInstance();
    }

    @java.lang.Override
    public mayton.emp.Emp build() {
      mayton.emp.Emp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public mayton.emp.Emp buildPartial() {
      mayton.emp.Emp result = new mayton.emp.Emp(this);
      result.empId_ = empId_;
      result.ename_ = ename_;
      result.job_ = job_;
      result.mgr_ = mgr_;
      result.hiredate_ = hiredate_;
      result.sal_ = sal_;
      result.comm_ = comm_;
      result.comments_ = comments_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }

    private int empId_ ;
    /**
     * <code>int32 empId = 1;</code>
     */
    public int getEmpId() {
      return empId_;
    }
    /**
     * <code>int32 empId = 1;</code>
     */
    public Builder setEmpId(int value) {
      
      empId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 empId = 1;</code>
     */
    public Builder clearEmpId() {
      
      empId_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object ename_ = "";
    /**
     * <code>string ename = 2;</code>
     */
    public java.lang.String getEname() {
      java.lang.Object ref = ename_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        ename_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string ename = 2;</code>
     */
    public com.google.protobuf.ByteString
        getEnameBytes() {
      java.lang.Object ref = ename_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        ename_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string ename = 2;</code>
     */
    public Builder setEname(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      ename_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string ename = 2;</code>
     */
    public Builder clearEname() {
      
      ename_ = getDefaultInstance().getEname();
      onChanged();
      return this;
    }
    /**
     * <code>string ename = 2;</code>
     */
    public Builder setEnameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      ename_ = value;
      onChanged();
      return this;
    }

    private int job_ = 0;
    /**
     * <code>.mayton.geo.Emp.Jobs job = 3;</code>
     */
    public int getJobValue() {
      return job_;
    }
    /**
     * <code>.mayton.geo.Emp.Jobs job = 3;</code>
     */
    public Builder setJobValue(int value) {
      job_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.mayton.geo.Emp.Jobs job = 3;</code>
     */
    public mayton.emp.Emp.Jobs getJob() {
      @SuppressWarnings("deprecation")
      mayton.emp.Emp.Jobs result = mayton.emp.Emp.Jobs.valueOf(job_);
      return result == null ? mayton.emp.Emp.Jobs.UNRECOGNIZED : result;
    }
    /**
     * <code>.mayton.geo.Emp.Jobs job = 3;</code>
     */
    public Builder setJob(mayton.emp.Emp.Jobs value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      job_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.mayton.geo.Emp.Jobs job = 3;</code>
     */
    public Builder clearJob() {
      
      job_ = 0;
      onChanged();
      return this;
    }

    private int mgr_ ;
    /**
     * <code>int32 mgr = 4;</code>
     */
    public int getMgr() {
      return mgr_;
    }
    /**
     * <code>int32 mgr = 4;</code>
     */
    public Builder setMgr(int value) {
      
      mgr_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 mgr = 4;</code>
     */
    public Builder clearMgr() {
      
      mgr_ = 0;
      onChanged();
      return this;
    }

    private java.lang.Object hiredate_ = "";
    /**
     * <code>string hiredate = 5;</code>
     */
    public java.lang.String getHiredate() {
      java.lang.Object ref = hiredate_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        hiredate_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string hiredate = 5;</code>
     */
    public com.google.protobuf.ByteString
        getHiredateBytes() {
      java.lang.Object ref = hiredate_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        hiredate_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string hiredate = 5;</code>
     */
    public Builder setHiredate(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      hiredate_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string hiredate = 5;</code>
     */
    public Builder clearHiredate() {
      
      hiredate_ = getDefaultInstance().getHiredate();
      onChanged();
      return this;
    }
    /**
     * <code>string hiredate = 5;</code>
     */
    public Builder setHiredateBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      hiredate_ = value;
      onChanged();
      return this;
    }

    private double sal_ ;
    /**
     * <code>double sal = 6;</code>
     */
    public double getSal() {
      return sal_;
    }
    /**
     * <code>double sal = 6;</code>
     */
    public Builder setSal(double value) {
      
      sal_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double sal = 6;</code>
     */
    public Builder clearSal() {
      
      sal_ = 0D;
      onChanged();
      return this;
    }

    private double comm_ ;
    /**
     * <code>double comm = 7;</code>
     */
    public double getComm() {
      return comm_;
    }
    /**
     * <code>double comm = 7;</code>
     */
    public Builder setComm(double value) {
      
      comm_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>double comm = 7;</code>
     */
    public Builder clearComm() {
      
      comm_ = 0D;
      onChanged();
      return this;
    }

    private java.lang.Object comments_ = "";
    /**
     * <code>string comments = 8 [deprecated = true];</code>
     */
    @java.lang.Deprecated public java.lang.String getComments() {
      java.lang.Object ref = comments_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        comments_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string comments = 8 [deprecated = true];</code>
     */
    @java.lang.Deprecated public com.google.protobuf.ByteString
        getCommentsBytes() {
      java.lang.Object ref = comments_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        comments_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string comments = 8 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder setComments(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      comments_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string comments = 8 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder clearComments() {
      
      comments_ = getDefaultInstance().getComments();
      onChanged();
      return this;
    }
    /**
     * <code>string comments = 8 [deprecated = true];</code>
     */
    @java.lang.Deprecated public Builder setCommentsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      comments_ = value;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:mayton.geo.Emp)
  }

  // @@protoc_insertion_point(class_scope:mayton.geo.Emp)
  private static final mayton.emp.Emp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new mayton.emp.Emp();
  }

  public static mayton.emp.Emp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Emp>
      PARSER = new com.google.protobuf.AbstractParser<Emp>() {
    @java.lang.Override
    public Emp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(
                builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Emp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Emp> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public mayton.emp.Emp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

