// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto3/emp.proto

package mayton.emp;

public interface EmpOrBuilder extends
    // @@protoc_insertion_point(interface_extends:mayton.geo.Emp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 empId = 1;</code>
   */
  int getEmpId();

  /**
   * <code>string ename = 2;</code>
   */
  java.lang.String getEname();
  /**
   * <code>string ename = 2;</code>
   */
  com.google.protobuf.ByteString
      getEnameBytes();

  /**
   * <code>.mayton.geo.Emp.Jobs job = 3;</code>
   */
  int getJobValue();
  /**
   * <code>.mayton.geo.Emp.Jobs job = 3;</code>
   */
  mayton.emp.Emp.Jobs getJob();

  /**
   * <code>int32 mgr = 4;</code>
   */
  int getMgr();

  /**
   * <code>string hiredate = 5;</code>
   */
  java.lang.String getHiredate();
  /**
   * <code>string hiredate = 5;</code>
   */
  com.google.protobuf.ByteString
      getHiredateBytes();

  /**
   * <code>double sal = 6;</code>
   */
  double getSal();

  /**
   * <code>double comm = 7;</code>
   */
  double getComm();

  /**
   * <code>string comments = 8 [deprecated = true];</code>
   */
  @java.lang.Deprecated java.lang.String getComments();
  /**
   * <code>string comments = 8 [deprecated = true];</code>
   */
  @java.lang.Deprecated com.google.protobuf.ByteString
      getCommentsBytes();
}
