// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: proto3/emp.proto

package mayton.emp;

public final class EmpOuterClass {
  private EmpOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mayton_geo_Debt_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mayton_geo_Debt_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_mayton_geo_Emp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_mayton_geo_Emp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020proto3/emp.proto\022\nmayton.geo\032\031google/p" +
      "rotobuf/any.proto\"\203\001\n\004Debt\022\016\n\006deptNo\030\001 \001" +
      "(\005\022\020\n\010debtName\030\002 \001(\t\022\013\n\003loc\030\003 \001(\t\022\035\n\004emp" +
      "s\030\004 \003(\0132\017.mayton.geo.Emp\022\'\n\tanyObject\030\005 " +
      "\001(\0132\024.google.protobuf.AnyJ\004\010\006\020\025\"\346\001\n\003Emp\022" +
      "\r\n\005empId\030\001 \001(\005\022\r\n\005ename\030\002 \001(\t\022!\n\003job\030\003 \001" +
      "(\0162\024.mayton.geo.Emp.Jobs\022\013\n\003mgr\030\004 \001(\005\022\020\n" +
      "\010hiredate\030\005 \001(\t\022\013\n\003sal\030\006 \001(\001\022\014\n\004comm\030\007 \001" +
      "(\001\022\024\n\010comments\030\010 \001(\tB\002\030\001\"H\n\004Jobs\022\014\n\010SALE" +
      "SMAN\020\000\022\r\n\tPRESIDENT\020\001\022\013\n\007ANALYST\020\002\022\t\n\005CL" +
      "ERK\020\003\022\013\n\007MANAGER\020\004J\004\010\t\020eB\020\n\nmayton.empH\002" +
      "P\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        }, assigner);
    internal_static_mayton_geo_Debt_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_mayton_geo_Debt_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mayton_geo_Debt_descriptor,
        new java.lang.String[] { "DeptNo", "DebtName", "Loc", "Emps", "AnyObject", });
    internal_static_mayton_geo_Emp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_mayton_geo_Emp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_mayton_geo_Emp_descriptor,
        new java.lang.String[] { "EmpId", "Ename", "Job", "Mgr", "Hiredate", "Sal", "Comm", "Comments", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
