/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef cross-platform-service_CONSTANTS_H
#define cross-platform-service_CONSTANTS_H

#include "cross-platform-service_types.h"

namespace com { namespace baeldung { namespace thrift { namespace impl {

class cross-platform-serviceConstants {
 public:
  cross-platform-serviceConstants();

};

extern const cross-platform-serviceConstants g_cross-platform-service_constants;

}}}} // namespace

#endif
