// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "CrossPlatformService.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using namespace  ::com::baeldung::thrift::impl;

class CrossPlatformServiceHandler : virtual public CrossPlatformServiceIf {
 public:
  CrossPlatformServiceHandler() {
    // Your initialization goes here
  }

  void get(CrossPlatformResource& _return, const int32_t id) {
    // Your implementation goes here
    printf("get\n");
  }

  void save(const CrossPlatformResource& resource) {
    // Your implementation goes here
    printf("save\n");
  }

  void getList(std::vector<CrossPlatformResource> & _return) {
    // Your implementation goes here
    printf("getList\n");
  }

  bool ping() {
    // Your implementation goes here
    printf("ping\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  ::std::shared_ptr<CrossPlatformServiceHandler> handler(new CrossPlatformServiceHandler());
  ::std::shared_ptr<TProcessor> processor(new CrossPlatformServiceProcessor(handler));
  ::std::shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  ::std::shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  ::std::shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

