/**
 * Autogenerated by Thrift Compiler (0.13.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "cross-platform-service_constants.h"

namespace com { namespace baeldung { namespace thrift { namespace impl {

const cross-platform-serviceConstants g_cross-platform-service_constants;

cross-platform-serviceConstants::cross-platform-serviceConstants() {
}

}}}} // namespace

