/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package mayton.probeavro.emp;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class Debt extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -8574906535693954255L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"Debt\",\"namespace\":\"mayton.probeavro.emp\",\"fields\":[{\"name\":\"DEBTNO\",\"type\":{\"type\":\"string\",\"logicalType\":\"UUID\"}},{\"name\":\"DEBTNAME\",\"type\":\"string\"},{\"name\":\"LOC\",\"type\":\"string\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<Debt> ENCODER =
      new BinaryMessageEncoder<Debt>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<Debt> DECODER =
      new BinaryMessageDecoder<Debt>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<Debt> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<Debt> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<Debt> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<Debt>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this Debt to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a Debt from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a Debt instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static Debt fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.CharSequence DEBTNO;
   private java.lang.CharSequence DEBTNAME;
   private java.lang.CharSequence LOC;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public Debt() {}

  /**
   * All-args constructor.
   * @param DEBTNO The new value for DEBTNO
   * @param DEBTNAME The new value for DEBTNAME
   * @param LOC The new value for LOC
   */
  public Debt(java.lang.CharSequence DEBTNO, java.lang.CharSequence DEBTNAME, java.lang.CharSequence LOC) {
    this.DEBTNO = DEBTNO;
    this.DEBTNAME = DEBTNAME;
    this.LOC = LOC;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return DEBTNO;
    case 1: return DEBTNAME;
    case 2: return LOC;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: DEBTNO = (java.lang.CharSequence)value$; break;
    case 1: DEBTNAME = (java.lang.CharSequence)value$; break;
    case 2: LOC = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'DEBTNO' field.
   * @return The value of the 'DEBTNO' field.
   */
  public java.lang.CharSequence getDEBTNO() {
    return DEBTNO;
  }


  /**
   * Sets the value of the 'DEBTNO' field.
   * @param value the value to set.
   */
  public void setDEBTNO(java.lang.CharSequence value) {
    this.DEBTNO = value;
  }

  /**
   * Gets the value of the 'DEBTNAME' field.
   * @return The value of the 'DEBTNAME' field.
   */
  public java.lang.CharSequence getDEBTNAME() {
    return DEBTNAME;
  }


  /**
   * Sets the value of the 'DEBTNAME' field.
   * @param value the value to set.
   */
  public void setDEBTNAME(java.lang.CharSequence value) {
    this.DEBTNAME = value;
  }

  /**
   * Gets the value of the 'LOC' field.
   * @return The value of the 'LOC' field.
   */
  public java.lang.CharSequence getLOC() {
    return LOC;
  }


  /**
   * Sets the value of the 'LOC' field.
   * @param value the value to set.
   */
  public void setLOC(java.lang.CharSequence value) {
    this.LOC = value;
  }

  /**
   * Creates a new Debt RecordBuilder.
   * @return A new Debt RecordBuilder
   */
  public static mayton.probeavro.emp.Debt.Builder newBuilder() {
    return new mayton.probeavro.emp.Debt.Builder();
  }

  /**
   * Creates a new Debt RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new Debt RecordBuilder
   */
  public static mayton.probeavro.emp.Debt.Builder newBuilder(mayton.probeavro.emp.Debt.Builder other) {
    if (other == null) {
      return new mayton.probeavro.emp.Debt.Builder();
    } else {
      return new mayton.probeavro.emp.Debt.Builder(other);
    }
  }

  /**
   * Creates a new Debt RecordBuilder by copying an existing Debt instance.
   * @param other The existing instance to copy.
   * @return A new Debt RecordBuilder
   */
  public static mayton.probeavro.emp.Debt.Builder newBuilder(mayton.probeavro.emp.Debt other) {
    if (other == null) {
      return new mayton.probeavro.emp.Debt.Builder();
    } else {
      return new mayton.probeavro.emp.Debt.Builder(other);
    }
  }

  /**
   * RecordBuilder for Debt instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<Debt>
    implements org.apache.avro.data.RecordBuilder<Debt> {

    private java.lang.CharSequence DEBTNO;
    private java.lang.CharSequence DEBTNAME;
    private java.lang.CharSequence LOC;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(mayton.probeavro.emp.Debt.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.DEBTNO)) {
        this.DEBTNO = data().deepCopy(fields()[0].schema(), other.DEBTNO);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.DEBTNAME)) {
        this.DEBTNAME = data().deepCopy(fields()[1].schema(), other.DEBTNAME);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.LOC)) {
        this.LOC = data().deepCopy(fields()[2].schema(), other.LOC);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing Debt instance
     * @param other The existing instance to copy.
     */
    private Builder(mayton.probeavro.emp.Debt other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.DEBTNO)) {
        this.DEBTNO = data().deepCopy(fields()[0].schema(), other.DEBTNO);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.DEBTNAME)) {
        this.DEBTNAME = data().deepCopy(fields()[1].schema(), other.DEBTNAME);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.LOC)) {
        this.LOC = data().deepCopy(fields()[2].schema(), other.LOC);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'DEBTNO' field.
      * @return The value.
      */
    public java.lang.CharSequence getDEBTNO() {
      return DEBTNO;
    }


    /**
      * Sets the value of the 'DEBTNO' field.
      * @param value The value of 'DEBTNO'.
      * @return This builder.
      */
    public mayton.probeavro.emp.Debt.Builder setDEBTNO(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.DEBTNO = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'DEBTNO' field has been set.
      * @return True if the 'DEBTNO' field has been set, false otherwise.
      */
    public boolean hasDEBTNO() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'DEBTNO' field.
      * @return This builder.
      */
    public mayton.probeavro.emp.Debt.Builder clearDEBTNO() {
      DEBTNO = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'DEBTNAME' field.
      * @return The value.
      */
    public java.lang.CharSequence getDEBTNAME() {
      return DEBTNAME;
    }


    /**
      * Sets the value of the 'DEBTNAME' field.
      * @param value The value of 'DEBTNAME'.
      * @return This builder.
      */
    public mayton.probeavro.emp.Debt.Builder setDEBTNAME(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.DEBTNAME = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'DEBTNAME' field has been set.
      * @return True if the 'DEBTNAME' field has been set, false otherwise.
      */
    public boolean hasDEBTNAME() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'DEBTNAME' field.
      * @return This builder.
      */
    public mayton.probeavro.emp.Debt.Builder clearDEBTNAME() {
      DEBTNAME = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'LOC' field.
      * @return The value.
      */
    public java.lang.CharSequence getLOC() {
      return LOC;
    }


    /**
      * Sets the value of the 'LOC' field.
      * @param value The value of 'LOC'.
      * @return This builder.
      */
    public mayton.probeavro.emp.Debt.Builder setLOC(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.LOC = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'LOC' field has been set.
      * @return True if the 'LOC' field has been set, false otherwise.
      */
    public boolean hasLOC() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'LOC' field.
      * @return This builder.
      */
    public mayton.probeavro.emp.Debt.Builder clearLOC() {
      LOC = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public Debt build() {
      try {
        Debt record = new Debt();
        record.DEBTNO = fieldSetFlags()[0] ? this.DEBTNO : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.DEBTNAME = fieldSetFlags()[1] ? this.DEBTNAME : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.LOC = fieldSetFlags()[2] ? this.LOC : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<Debt>
    WRITER$ = (org.apache.avro.io.DatumWriter<Debt>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<Debt>
    READER$ = (org.apache.avro.io.DatumReader<Debt>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.DEBTNO);

    out.writeString(this.DEBTNAME);

    out.writeString(this.LOC);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.DEBTNO = in.readString(this.DEBTNO instanceof Utf8 ? (Utf8)this.DEBTNO : null);

      this.DEBTNAME = in.readString(this.DEBTNAME instanceof Utf8 ? (Utf8)this.DEBTNAME : null);

      this.LOC = in.readString(this.LOC instanceof Utf8 ? (Utf8)this.LOC : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.DEBTNO = in.readString(this.DEBTNO instanceof Utf8 ? (Utf8)this.DEBTNO : null);
          break;

        case 1:
          this.DEBTNAME = in.readString(this.DEBTNAME instanceof Utf8 ? (Utf8)this.DEBTNAME : null);
          break;

        case 2:
          this.LOC = in.readString(this.LOC instanceof Utf8 ? (Utf8)this.LOC : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










