/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package mayton.probeavro.emp;
@org.apache.avro.specific.AvroGenerated
public enum JOBEnum implements org.apache.avro.generic.GenericEnumSymbol<JOBEnum> {
  SALESMAN, PRESIDENT, MANAGER, CLERK  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"JOBEnum\",\"namespace\":\"mayton.probeavro.emp\",\"symbols\":[\"SALESMAN\",\"PRESIDENT\",\"MANAGER\",\"CLERK\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
