/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GcdJni */

#ifndef _Included_GcdJni
#define _Included_GcdJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GcdJni
 * Method:    gcd
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_GcdJni_gcd
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
