/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class PrimeJni */

#ifndef _Included_PrimeJni
#define _Included_PrimeJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     PrimeJni
 * Method:    gcd
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_PrimeJni_gcd
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     PrimeJni
 * Method:    lcm
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_PrimeJni_lcm
  (JNIEnv *, jclass, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
